<?php $this->flash->output() ?>
<form method='post'>
    <p>
        <label>First Name</label>
        <?= $form->render('firstName') ?>
    </p>
    <p>
        <label>Last Name</label>
        <?= $form->render('lastName') ?>
    </p>
    <p>
        <label>Email</label>
        <?= $form->render('email') ?>
    </p>
    <p>
        <label>Password</label>
        <?= $form->render('password') ?>
    </p>
    <p>
        <label>User Type</label>
        <?= $form->render('userType') ?>
    </p>
    <p>
        <input type='submit' value='Save' />
    </p>
</form>